### ISSUE TITLE
toJson - not *quite* working .. 

### ISSUE THREAD

**Issue by mfrederico** [vlucas/phpDataMapper#4]
It appears the toJson is missing a function called "getData()"

I'm assuming it's supposed to aggregate all the data that comes in (even m:n) and spit it out as a json object.  This is exactly what I need.  I really hope your project is not dead!

**Comment by vlucas** [comment]
Fixed in commit:
http://github.com/vlucas/phpDataMapper/commit/5634c09768f19caaa4cb2889f0d3400345a129f5

It currently does not, however, drive down into the relations to retrieve them as well at the moment. That would be fairly easy to add with a recursive function that loops over all the fields and checks if the field is a relation. Consider taking a stab at the code, and I'll add it in.
